<?php

namespace App\Services;

use App\Models\Admission;
use App\Models\Bill;
use App\Models\LabOrder;
use App\Models\PharmacySale;
use App\Models\RadiologyOrder;
use Carbon\Carbon;
use Illuminate\Validation\ValidationException;

/**
 * Accumulates IPD charges into one final bill at discharge, per the spec:
 * room, medicine, laboratory and radiology are auto-aggregated from the
 * records already generated by their own modules during the admission
 * window; nursing/doctor/OT/consumable/other charges (no rate tables of
 * their own yet) are added by billing staff afterwards via
 * BillingService::addItem() on the same bill.
 */
class IpdBillingService
{
    public function __construct(private readonly BillingService $billingService) {}

    public function generateFinalBill(Admission $admission): Bill
    {
        if ($admission->status !== 'discharged') {
            throw ValidationException::withMessages([
                'status' => ['The final bill can only be generated after the patient has been discharged.'],
            ]);
        }

        $periodStart = $admission->admission_date;
        $periodEnd = $admission->discharge_date ?? now();

        $items = [
            ...$this->roomChargeItems($admission),
            ...$this->pharmacyChargeItems($admission, $periodStart, $periodEnd),
            ...$this->labChargeItems($admission, $periodStart, $periodEnd),
            ...$this->radiologyChargeItems($admission, $periodStart, $periodEnd),
        ];

        return $this->billingService->create([
            'patient_id' => $admission->patient_id,
            'type' => 'ipd',
            'source_type' => Admission::class,
            'source_id' => $admission->id,
            'items' => $items,
        ]);
    }

    private function roomChargeItems(Admission $admission): array
    {
        return $admission->bedAllocations()
            ->with('bed.room')
            ->get()
            ->filter(fn ($allocation) => $allocation->bed->room->daily_rate !== null)
            ->map(function ($allocation) {
                $end = $allocation->released_at ?? now();
                $days = max(1, (int) ceil(Carbon::parse($allocation->allocated_at)->diffInHours($end) / 24));

                return [
                    'category' => 'room',
                    'description' => "Room charges - Bed {$allocation->bed->bed_number} ({$days} day(s))",
                    'quantity' => $days,
                    'unit_price' => $allocation->bed->room->daily_rate,
                ];
            })
            ->values()
            ->all();
    }

    private function pharmacyChargeItems(Admission $admission, $start, $end): array
    {
        return PharmacySale::query()
            ->where('patient_id', $admission->patient_id)
            ->whereBetween('created_at', [$start, $end])
            ->where('status', 'completed')
            ->get()
            ->map(fn (PharmacySale $sale) => [
                'category' => 'medicine',
                'description' => "Pharmacy sale {$sale->invoice_number}",
                'quantity' => 1,
                'unit_price' => $sale->net_amount,
            ])
            ->all();
    }

    private function labChargeItems(Admission $admission, $start, $end): array
    {
        return LabOrder::query()
            ->where('patient_id', $admission->patient_id)
            ->whereBetween('ordered_at', [$start, $end])
            ->with('items.test')
            ->get()
            ->flatMap(fn (LabOrder $order) => $order->items->map(fn ($item) => [
                'category' => 'laboratory',
                'description' => "Lab test: {$item->test->name}",
                'quantity' => 1,
                'unit_price' => $item->test->price ?? 0,
            ]))
            ->all();
    }

    private function radiologyChargeItems(Admission $admission, $start, $end): array
    {
        return RadiologyOrder::query()
            ->where('patient_id', $admission->patient_id)
            ->whereBetween('ordered_at', [$start, $end])
            ->with('test')
            ->get()
            ->map(fn (RadiologyOrder $order) => [
                'category' => 'radiology',
                'description' => "Radiology: {$order->test->name}",
                'quantity' => 1,
                'unit_price' => $order->test->price ?? 0,
            ])
            ->all();
    }
}
